### ISSUE TITLE
java.lang.NullPointerException at com.funkyandroid.droidcon.uk.iosched.ui.MapFragment.showFloor(MapFragment.java:347)

### ISSUE THREAD

**Issue by alsutton** [droidcon/iosched#10]
Crash report from the Play Store;

java.lang.NullPointerException
at com.funkyandroid.droidcon.uk.iosched.ui.MapFragment.showFloor(MapFragment.java:347)
at com.funkyandroid.droidcon.uk.iosched.ui.MapFragment.access$000(MapFragment.java:80)
at com.funkyandroid.droidcon.uk.iosched.ui.MapFragment$2.onClick(MapFragment.java:209)
at android.view.View.performClick(View.java:4354)
at android.view.View$PerformClick.run(View.java:17962)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5328)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)

**Comment by alsutton** [comment]
Mapping is being disabled, most likely a side effect of not having data.
