### ISSUE TITLE
android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 6 at android.database.AbstractCursor.checkPosition(AbstractCursor.java:424)

### ISSUE THREAD

**Issue by alsutton** [droidcon/iosched#13]
Crash from Google Play Developers Console;

android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 6
at android.database.AbstractCursor.checkPosition(AbstractCursor.java:424)
at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
at android.database.CursorWrapper.getString(CursorWrapper.java:114)
at com.funkyandroid.droidcon.uk.iosched.ui.ExploreFragment.onListItemClick(ExploreFragment.java:159)
at android.support.v4.app.ListFragment$2.onItemClick(ListFragment.java:58)
at android.widget.AdapterView.performItemClick(AdapterView.java:298)
at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:2788)
at android.widget.AbsListView$1.run(AbsListView.java:3463)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)

**Comment by alsutton** [comment]
Fixed by https://github.com/droidcon/iosched/commit/4bcd3f3b8be83d0ce3f0009a85c517bcf087a530
