### ISSUE TITLE
CursorIndexOutOfBoundsException when tapping (All tracks) in the Explore list

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#15]
09-16 09:54:59.636  23193-23193/com.funkyandroid.droidcon.uk.iosched E/AndroidRuntime﹕ FATAL EXCEPTION: main
        android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 16
        at android.database.AbstractCursor.checkPosition(AbstractCursor.java:424)
        at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
        at android.database.CursorWrapper.getString(CursorWrapper.java:114)
        at com.funkyandroid.droidcon.uk.iosched.ui.ExploreFragment.onListItemClick(ExploreFragment.java:159)
        at android.support.v4.app.ListFragment$2.onItemClick(ListFragment.java:58)
        at android.widget.AdapterView.performItemClick(AdapterView.java:298)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:2749)
        at android.widget.AbsListView$1.run(AbsListView.java:3423)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5227)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by alsutton** [comment]
Isn't this the same as issue #13 ?

**Comment by rock3r** [comment]
I think it is. I somehow missed #13, sorry! Definitely a dupe.
