### ISSUE TITLE
Crash on tapping a session for details

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#2]
When tapping a session in the schedule, the app crashes:

```
09-11 16:59:08.110  25122-25122/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
        android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.funkyandroid.droidcon.uk.iosched/blocks/1368647100-1368650700/sessions (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1622)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1417)
        at android.app.Activity.startActivityForResult(Activity.java:3370)
        at android.app.Activity.startActivityForResult(Activity.java:3331)
        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:833)
        at android.support.v4.app.Fragment.startActivity(Fragment.java:856)
        at com.funkyandroid.droidcon.uk.iosched.ui.ScheduleFragment$MyScheduleAdapter$1.onClick(ScheduleFragment.java:367)
        at android.view.View.performClick(View.java:4211)
        at android.view.View$PerformClick.run(View.java:17362)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5227)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
        at dalvik.system.NativeStart.main(Native Method)
```

This is probably due to one of the `intent-filters` defined in the manifest for `SessionDetailsActivity`. I strongly suspect you'd have to change the `data` tag contents for the filter you can find at lines 221-228 of the manifest file.

I'd change it myself but I don't know the URLs you're defining for your webservice.

**Comment by alsutton** [comment]
Should be resolved.
