### ISSUE TITLE
java.lang.NullPointerException at com.funkyandroid.droidcon.uk.iosched.ui.BaseActivity.setActionBarTrackIcon(BaseActivity.java:61)

### ISSUE THREAD

**Issue by alsutton** [droidcon/iosched#9]
Crash report from the Play Store Console;

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.funkyandroid.droidcon.uk.iosched/com.funkyandroid.droidcon.uk.iosched.ui.phone.TrackDetailActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2247)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2297)
at android.app.ActivityThread.access$700(ActivityThread.java:152)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5328)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.funkyandroid.droidcon.uk.iosched.ui.BaseActivity.setActionBarTrackIcon(BaseActivity.java:61)
at com.funkyandroid.droidcon.uk.iosched.ui.phone.TrackDetailActivity.onTrackInfoAvailable(TrackDetailActivity.java:209)
at com.funkyandroid.droidcon.uk.iosched.ui.TrackInfoHelperFragment.onCreate(TrackInfoHelperFragment.java:92)
at android.support.v4.app.Fragment.performCreate(Fragment.java:1455)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:893)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1872)
at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:215)
at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:97)
at com.funkyandroid.droidcon.uk.iosched.ui.BaseActivity.onCreate(BaseActivity.java:40)
at com.funkyandroid.droidcon.uk.iosched.ui.phone.TrackDetailActivity.onCreate(TrackDetailActivity.java:63)
at android.app.Activity.performCreate(Activity.java:5250)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
... 11 more

**Comment by alsutton** [comment]
Failing line;

```
        getSupportActionBar().setIcon(R.drawable.actionbar_icon);
```

Needs investigation to see why the action bar wouldn't be present on the device.

**Comment by alsutton** [comment]
Unable to reproduce. Has not been seen in more recent versions.

Closing.
